// ========== 단어 데이터 ==========
// 총 20개 레벨, 약 615개 단어

const levelData = {
    // ========== Level 1: 35개 단어 ==========
    1: [
        {id:1,english:"consequence",korean:"결과",pos:"noun",example:"This has serious consequences.",korExample:"이것은 심각한 결과를 초래합니다."},
        {id:2,english:"phenomenon",korean:"현상",pos:"noun",example:"A natural phenomenon.",korExample:"자연 현상입니다."},
        {id:3,english:"fundamental",korean:"근본적인",pos:"adjective",example:"A fundamental principle.",korExample:"근본적인 원칙입니다."},
        {id:4,english:"aspect",korean:"측면",pos:"noun",example:"Consider every aspect.",korExample:"모든 측면을 고려하세요."},
        {id:5,english:"approach",korean:"접근법",pos:"noun",example:"A different approach.",korExample:"다른 접근법입니다."},
        {id:6,english:"perspective",korean:"관점",pos:"noun",example:"From my perspective.",korExample:"제 관점에서는요."},
        {id:7,english:"constitute",korean:"구성하다",pos:"verb",example:"These constitute the whole.",korExample:"이것들이 전체를 구성합니다."},
        {id:8,english:"implement",korean:"시행하다",pos:"verb",example:"Implement the plan.",korExample:"계획을 시행하세요."},
        {id:9,english:"enhance",korean:"향상시키다",pos:"verb",example:"Enhance your skills.",korExample:"기술을 향상시키세요."},
        {id:10,english:"demonstrate",korean:"입증하다",pos:"verb",example:"Demonstrate your ability.",korExample:"능력을 입증하세요."},
        {id:11,english:"significant",korean:"중요한",pos:"adjective",example:"A significant change.",korExample:"중요한 변화입니다."},
        {id:12,english:"sufficient",korean:"충분한",pos:"adjective",example:"Sufficient evidence.",korExample:"충분한 증거입니다."},
        {id:13,english:"comprehensive",korean:"포괄적인",pos:"adjective",example:"A comprehensive review.",korExample:"포괄적인 검토입니다."},
        {id:14,english:"diverse",korean:"다양한",pos:"adjective",example:"Diverse opinions.",korExample:"다양한 의견들입니다."},
        {id:15,english:"explicit",korean:"명시적인",pos:"adjective",example:"Explicit instructions.",korExample:"명시적인 지시사항입니다."},
        {id:16,english:"inevitable",korean:"불가피한",pos:"adjective",example:"An inevitable result.",korExample:"불가피한 결과입니다."},
        {id:17,english:"prominent",korean:"두드러진",pos:"adjective",example:"A prominent figure.",korExample:"두드러진 인물입니다."},
        {id:18,english:"substantial",korean:"상당한",pos:"adjective",example:"Substantial progress.",korExample:"상당한 진전입니다."},
        {id:19,english:"tentative",korean:"잠정적인",pos:"adjective",example:"A tentative plan.",korExample:"잠정적인 계획입니다."},
        {id:20,english:"arbitrary",korean:"임의적인",pos:"adjective",example:"An arbitrary decision.",korExample:"임의적인 결정입니다."},
        {id:21,english:"acknowledge",korean:"인정하다",pos:"verb",example:"Acknowledge the truth.",korExample:"진실을 인정하세요."},
        {id:22,english:"anticipate",korean:"예상하다",pos:"verb",example:"Anticipate problems.",korExample:"문제를 예상하세요."},
        {id:23,english:"comprehend",korean:"이해하다",pos:"verb",example:"Comprehend the concept.",korExample:"개념을 이해하세요."},
        {id:24,english:"discern",korean:"식별하다",pos:"verb",example:"Discern the difference.",korExample:"차이를 식별하세요."},
        {id:25,english:"elaborate",korean:"상세히 설명하다",pos:"verb",example:"Elaborate on your idea.",korExample:"아이디어를 상세히 설명하세요."},
        {id:26,english:"formulate",korean:"공식화하다",pos:"verb",example:"Formulate a strategy.",korExample:"전략을 공식화하세요."},
        {id:27,english:"initiate",korean:"시작하다",pos:"verb",example:"Initiate the process.",korExample:"과정을 시작하세요."},
        {id:28,english:"manipulate",korean:"조작하다",pos:"verb",example:"Manipulate the data.",korExample:"데이터를 조작하다."},
        {id:29,english:"perceive",korean:"인식하다",pos:"verb",example:"Perceive the reality.",korExample:"현실을 인식하세요."},
        {id:30,english:"refine",korean:"개선하다",pos:"verb",example:"Refine your technique.",korExample:"기술을 개선하세요."},
        {id:31,english:"synthesis",korean:"종합",pos:"noun",example:"A synthesis of ideas.",korExample:"아이디어의 종합입니다."},
        {id:32,english:"proportion",korean:"비율",pos:"noun",example:"The right proportion.",korExample:"올바른 비율입니다."},
        {id:33,english:"criterion",korean:"기준",pos:"noun",example:"Meet the criterion.",korExample:"기준을 충족하세요."},
        {id:34,english:"hypothesis",korean:"가설",pos:"noun",example:"Test the hypothesis.",korExample:"가설을 검증하세요."},
        {id:35,english:"context",korean:"맥락",pos:"noun",example:"Understand the context.",korExample:"맥락을 이해하세요."}
    ],

    // ========== Level 2: 35개 단어 ==========
    2: [
        {id:1,english:"infrastructure",korean:"기반시설",pos:"noun",example:"Build infrastructure.",korExample:"기반시설을 건설하세요."},
        {id:2,english:"sovereignty",korean:"주권",pos:"noun",example:"National sovereignty.",korExample:"국가 주권입니다."},
        {id:3,english:"authenticity",korean:"진정성",pos:"noun",example:"Question its authenticity.",korExample:"진정성을 의심하세요."},
        {id:4,english:"designation",korean:"지정",pos:"noun",example:"Official designation.",korExample:"공식 지정입니다."},
        {id:5,english:"equilibrium",korean:"균형",pos:"noun",example:"Maintain equilibrium.",korExample:"균형을 유지하세요."},
        {id:6,english:"proliferation",korean:"확산",pos:"noun",example:"Nuclear proliferation.",korExample:"핵 확산입니다."},
        {id:7,english:"predecessor",korean:"전임자",pos:"noun",example:"My predecessor left.",korExample:"제 전임자가 떠났습니다."},
        {id:8,english:"counterpart",korean:"상대방",pos:"noun",example:"Meet your counterpart.",korExample:"상대방을 만나세요."},
        {id:9,english:"ambiguity",korean:"모호함",pos:"noun",example:"Remove the ambiguity.",korExample:"모호함을 제거하세요."},
        {id:10,english:"encompass",korean:"포함하다",pos:"verb",example:"Encompass all aspects.",korExample:"모든 측면을 포함하세요."},
        {id:11,english:"facilitate",korean:"촉진하다",pos:"verb",example:"Facilitate discussion.",korExample:"토론을 촉진하세요."},
        {id:12,english:"substantiate",korean:"입증하다",pos:"verb",example:"Substantiate your claim.",korExample:"주장을 입증하세요."},
        {id:13,english:"differentiate",korean:"구별하다",pos:"verb",example:"Differentiate between them.",korExample:"그것들을 구별하세요."},
        {id:14,english:"consolidate",korean:"통합하다",pos:"verb",example:"Consolidate power.",korExample:"권력을 통합하세요."},
        {id:15,english:"deteriorate",korean:"악화되다",pos:"verb",example:"Conditions deteriorate.",korExample:"상황이 악화됩니다."},
        {id:16,english:"perpetuate",korean:"영속화하다",pos:"verb",example:"Perpetuate the tradition.",korExample:"전통을 영속화하세요."},
        {id:17,english:"subordinate",korean:"종속시키다",pos:"verb",example:"Subordinate to authority.",korExample:"권위에 종속시키다."},
        {id:18,english:"prevalent",korean:"만연한",pos:"adjective",example:"A prevalent belief.",korExample:"만연한 믿음입니다."},
        {id:19,english:"coherent",korean:"일관된",pos:"adjective",example:"A coherent argument.",korExample:"일관된 주장입니다."},
        {id:20,english:"ambiguous",korean:"애매한",pos:"adjective",example:"An ambiguous answer.",korExample:"애매한 답변입니다."},
        {id:21,english:"plausible",korean:"그럴듯한",pos:"adjective",example:"A plausible explanation.",korExample:"그럴듯한 설명입니다."},
        {id:22,english:"rigorous",korean:"엄격한",pos:"adjective",example:"Rigorous standards.",korExample:"엄격한 기준입니다."},
        {id:23,english:"obsolete",korean:"쓸모없는",pos:"adjective",example:"Obsolete technology.",korExample:"쓸모없는 기술입니다."},
        {id:24,english:"concurrent",korean:"동시의",pos:"adjective",example:"Concurrent events.",korExample:"동시의 사건들입니다."},
        {id:25,english:"intrinsic",korean:"본질적인",pos:"adjective",example:"Intrinsic value.",korExample:"본질적인 가치입니다."},
        {id:26,english:"inherent",korean:"내재된",pos:"adjective",example:"Inherent risk.",korExample:"내재된 위험입니다."},
        {id:27,english:"preliminary",korean:"예비의",pos:"adjective",example:"Preliminary results.",korExample:"예비 결과입니다."},
        {id:28,english:"terminology",korean:"용어",pos:"noun",example:"Technical terminology.",korExample:"기술 용어입니다."},
        {id:29,english:"analogy",korean:"유추",pos:"noun",example:"Draw an analogy.",korExample:"유추를 하세요."},
        {id:30,english:"entity",korean:"실체",pos:"noun",example:"A legal entity.",korExample:"법적 실체입니다."},
        {id:31,english:"remnant",korean:"잔재",pos:"noun",example:"A remnant of the past.",korExample:"과거의 잔재입니다."},
        {id:32,english:"spectrum",korean:"범위",pos:"noun",example:"A wide spectrum.",korExample:"넓은 범위입니다."},
        {id:33,english:"excerpt",korean:"발췌",pos:"noun",example:"An excerpt from a book.",korExample:"책에서의 발췌입니다."},
        {id:34,english:"notion",korean:"개념",pos:"noun",example:"A vague notion.",korExample:"모호한 개념입니다."},
        {id:35,english:"doctrine",korean:"교리",pos:"noun",example:"Religious doctrine.",korExample:"종교적 교리입니다."}
    ],

    // ========== Level 3: 35개 단어 ==========
    3: [
        {id:1,english:"disposition",korean:"성향",pos:"noun",example:"A cheerful disposition.",korExample:"쾌활한 성향입니다."},
        {id:2,english:"inclination",korean:"경향",pos:"noun",example:"A natural inclination.",korExample:"자연스러운 경향입니다."},
        {id:3,english:"integrity",korean:"완전성",pos:"noun",example:"Structural integrity.",korExample:"구조적 완전성입니다."},
        {id:4,english:"constraint",korean:"제약",pos:"noun",example:"Budget constraints.",korExample:"예산 제약입니다."},
        {id:5,english:"implication",korean:"함의",pos:"noun",example:"The implication is clear.",korExample:"함의가 명확합니다."},
        {id:6,english:"manifestation",korean:"표출",pos:"noun",example:"A manifestation of fear.",korExample:"두려움의 표출입니다."},
        {id:7,english:"proposition",korean:"제안",pos:"noun",example:"An interesting proposition.",korExample:"흥미로운 제안입니다."},
        {id:8,english:"discourse",korean:"담론",pos:"noun",example:"Political discourse.",korExample:"정치적 담론입니다."},
        {id:9,english:"correlation",korean:"상관관계",pos:"noun",example:"A strong correlation.",korExample:"강한 상관관계입니다."},
        {id:10,english:"exacerbate",korean:"악화시키다",pos:"verb",example:"Exacerbate the problem.",korExample:"문제를 악화시키다."},
        {id:11,english:"alleviate",korean:"완화하다",pos:"verb",example:"Alleviate the pain.",korExample:"고통을 완화하세요."},
        {id:12,english:"ascertain",korean:"확인하다",pos:"verb",example:"Ascertain the facts.",korExample:"사실을 확인하세요."},
        {id:13,english:"circumvent",korean:"우회하다",pos:"verb",example:"Circumvent the rules.",korExample:"규칙을 우회하다."},
        {id:14,english:"corroborate",korean:"확증하다",pos:"verb",example:"Corroborate the story.",korExample:"이야기를 확증하세요."},
        {id:15,english:"elucidate",korean:"명료하게 하다",pos:"verb",example:"Elucidate the concept.",korExample:"개념을 명료하게 하세요."},
        {id:16,english:"extrapolate",korean:"추정하다",pos:"verb",example:"Extrapolate from data.",korExample:"데이터에서 추정하세요."},
        {id:17,english:"preclude",korean:"배제하다",pos:"verb",example:"Preclude the possibility.",korExample:"가능성을 배제하세요."},
        {id:18,english:"vindicate",korean:"정당화하다",pos:"verb",example:"Vindicate her decision.",korExample:"그녀의 결정을 정당화하세요."},
        {id:19,english:"convoluted",korean:"복잡한",pos:"adjective",example:"A convoluted argument.",korExample:"복잡한 주장입니다."},
        {id:20,english:"meticulous",korean:"꼼꼼한",pos:"adjective",example:"Meticulous attention.",korExample:"꼼꼼한 주의입니다."},
        {id:21,english:"pragmatic",korean:"실용적인",pos:"adjective",example:"A pragmatic approach.",korExample:"실용적인 접근법입니다."},
        {id:22,english:"redundant",korean:"불필요한",pos:"adjective",example:"Redundant information.",korExample:"불필요한 정보입니다."},
        {id:23,english:"tangible",korean:"실질적인",pos:"adjective",example:"Tangible results.",korExample:"실질적인 결과입니다."},
        {id:24,english:"unequivocal",korean:"명백한",pos:"adjective",example:"An unequivocal statement.",korExample:"명백한 진술입니다."},
        {id:25,english:"viable",korean:"실행 가능한",pos:"adjective",example:"A viable solution.",korExample:"실행 가능한 해결책입니다."},
        {id:26,english:"volatile",korean:"변동성이 큰",pos:"adjective",example:"A volatile market.",korExample:"변동성이 큰 시장입니다."},
        {id:27,english:"adept",korean:"능숙한",pos:"adjective",example:"Adept at negotiation.",korExample:"협상에 능숙합니다."},
        {id:28,english:"astute",korean:"기민한",pos:"adjective",example:"An astute observation.",korExample:"기민한 관찰입니다."},
        {id:29,english:"delineation",korean:"서술",pos:"noun",example:"Clear delineation.",korExample:"명확한 서술입니다."},
        {id:30,english:"dichotomy",korean:"이분법",pos:"noun",example:"A false dichotomy.",korExample:"잘못된 이분법입니다."},
        {id:31,english:"anomaly",korean:"이상현상",pos:"noun",example:"Statistical anomaly.",korExample:"통계적 이상현상입니다."},
        {id:32,english:"epitome",korean:"전형",pos:"noun",example:"The epitome of elegance.",korExample:"우아함의 전형입니다."},
        {id:33,english:"endeavor",korean:"노력",pos:"noun",example:"A worthy endeavor.",korExample:"가치 있는 노력입니다."},
        {id:34,english:"magnitude",korean:"규모",pos:"noun",example:"The magnitude is huge.",korExample:"규모가 엄청납니다."},
        {id:35,english:"threshold",korean:"문턱",pos:"noun",example:"Cross the threshold.",korExample:"문턱을 넘으세요."}
    ],

    // ========== Level 4: 40개 단어 ==========
    4: [
        {id:1,english:"benevolent",korean:"자비로운",pos:"adjective",example:"A benevolent leader.",korExample:"자비로운 지도자입니다."},
        {id:2,english:"conscientious",korean:"성실한",pos:"adjective",example:"A conscientious worker.",korExample:"성실한 근로자입니다."},
        {id:3,english:"diligent",korean:"부지런한",pos:"adjective",example:"A diligent student.",korExample:"부지런한 학생입니다."},
        {id:4,english:"eloquent",korean:"웅변적인",pos:"adjective",example:"An eloquent speech.",korExample:"웅변적인 연설입니다."},
        {id:5,english:"fervent",korean:"열렬한",pos:"adjective",example:"Fervent support.",korExample:"열렬한 지지입니다."},
        {id:6,english:"gregarious",korean:"사교적인",pos:"adjective",example:"A gregarious person.",korExample:"사교적인 사람입니다."},
        {id:7,english:"tenacious",korean:"완강한",pos:"adjective",example:"Tenacious determination.",korExample:"완강한 결의입니다."},
        {id:8,english:"resilient",korean:"회복력있는",pos:"adjective",example:"A resilient economy.",korExample:"회복력있는 경제입니다."},
        {id:9,english:"scrupulous",korean:"세심한",pos:"adjective",example:"Scrupulous attention.",korExample:"세심한 주의입니다."},
        {id:10,english:"judicious",korean:"현명한",pos:"adjective",example:"A judicious decision.",korExample:"현명한 결정입니다."},
        {id:11,english:"reciprocate",korean:"보답하다",pos:"verb",example:"Reciprocate the favor.",korExample:"호의에 보답하세요."},
        {id:12,english:"relinquish",korean:"포기하다",pos:"verb",example:"Relinquish control.",korExample:"통제를 포기하세요."},
        {id:13,english:"scrutinize",korean:"정밀조사하다",pos:"verb",example:"Scrutinize the document.",korExample:"문서를 정밀조사하세요."},
        {id:14,english:"stipulate",korean:"규정하다",pos:"verb",example:"Stipulate the terms.",korExample:"조건을 규정하세요."},
        {id:15,english:"supersede",korean:"대체하다",pos:"verb",example:"Supersede old rules.",korExample:"기존 규칙을 대체하세요."},
        {id:16,english:"transcend",korean:"초월하다",pos:"verb",example:"Transcend limitations.",korExample:"한계를 초월하세요."},
        {id:17,english:"undermine",korean:"훼손하다",pos:"verb",example:"Undermine authority.",korExample:"권위를 훼손하다."},
        {id:18,english:"advocate",korean:"옹호하다",pos:"verb",example:"Advocate for change.",korExample:"변화를 옹호하세요."},
        {id:19,english:"articulate",korean:"명확히 표현하다",pos:"verb",example:"Articulate your vision.",korExample:"비전을 명확히 표현하세요."},
        {id:20,english:"ambivalence",korean:"양가감정",pos:"noun",example:"Feel ambivalence.",korExample:"양가감정을 느낍니다."},
        {id:21,english:"complacency",korean:"자기만족",pos:"noun",example:"Avoid complacency.",korExample:"자기만족을 피하세요."},
        {id:22,english:"discrepancy",korean:"불일치",pos:"noun",example:"A discrepancy exists.",korExample:"불일치가 존재합니다."},
        {id:23,english:"precedent",korean:"전례",pos:"noun",example:"Set a precedent.",korExample:"전례를 남기세요."},
        {id:24,english:"ramification",korean:"파급효과",pos:"noun",example:"Consider ramifications.",korExample:"파급효과를 고려하세요."},
        {id:25,english:"synopsis",korean:"개요",pos:"noun",example:"Read the synopsis.",korExample:"개요를 읽으세요."},
        {id:26,english:"tenure",korean:"재임기간",pos:"noun",example:"During his tenure.",korExample:"그의 재임기간 동안입니다."},
        {id:27,english:"trajectory",korean:"궤적",pos:"noun",example:"Career trajectory.",korExample:"경력 궤적입니다."},
        {id:28,english:"acumen",korean:"통찰력",pos:"noun",example:"Business acumen.",korExample:"사업 통찰력입니다."},
        {id:29,english:"catalyst",korean:"촉매",pos:"noun",example:"A catalyst for change.",korExample:"변화의 촉매입니다."},
        {id:30,english:"negligible",korean:"무시할 만한",pos:"adjective",example:"Negligible difference.",korExample:"무시할 만한 차이입니다."},
        {id:31,english:"mundane",korean:"평범한",pos:"adjective",example:"Mundane tasks.",korExample:"평범한 업무입니다."},
        {id:32,english:"pervasive",korean:"만연한",pos:"adjective",example:"Pervasive influence.",korExample:"만연한 영향입니다."},
        {id:33,english:"dormant",korean:"휴면상태의",pos:"adjective",example:"Dormant volcano.",korExample:"휴면상태의 화산입니다."},
        {id:34,english:"imminent",korean:"임박한",pos:"adjective",example:"Imminent danger.",korExample:"임박한 위험입니다."},
        {id:35,english:"pivotal",korean:"중추적인",pos:"adjective",example:"A pivotal moment.",korExample:"중추적인 순간입니다."},
        {id:36,english:"sporadic",korean:"산발적인",pos:"adjective",example:"Sporadic outbreaks.",korExample:"산발적인 발병입니다."},
        {id:37,english:"transient",korean:"일시적인",pos:"adjective",example:"Transient phenomenon.",korExample:"일시적인 현상입니다."},
        {id:38,english:"ubiquitous",korean:"어디에나 있는",pos:"adjective",example:"Ubiquitous technology.",korExample:"어디에나 있는 기술입니다."},
        {id:39,english:"prudent",korean:"신중한",pos:"adjective",example:"A prudent approach.",korExample:"신중한 접근법입니다."},
        {id:40,english:"fortuitous",korean:"우연한",pos:"adjective",example:"A fortuitous encounter.",korExample:"우연한 만남입니다."}
    ],

    // ========== Level 5: 40개 단어 ==========
    5: [
        {id:1,english:"ameliorate",korean:"개선하다",pos:"verb",example:"Ameliorate conditions.",korExample:"상황을 개선하세요."},
        {id:2,english:"obfuscate",korean:"모호하게 하다",pos:"verb",example:"Obfuscate the truth.",korExample:"진실을 모호하게 하다."},
        {id:3,english:"eradicate",korean:"근절하다",pos:"verb",example:"Eradicate poverty.",korExample:"빈곤을 근절하세요."},
        {id:4,english:"mitigate",korean:"완화하다",pos:"verb",example:"Mitigate the impact.",korExample:"영향을 완화하세요."},
        {id:5,english:"proliferate",korean:"급증하다",pos:"verb",example:"Weapons proliferate.",korExample:"무기가 급증합니다."},
        {id:6,english:"disseminate",korean:"보급하다",pos:"verb",example:"Disseminate information.",korExample:"정보를 보급하세요."},
        {id:7,english:"orchestrate",korean:"조직하다",pos:"verb",example:"Orchestrate a campaign.",korExample:"운동을 조직하세요."},
        {id:8,english:"repudiate",korean:"거부하다",pos:"verb",example:"Repudiate the claim.",korExample:"주장을 거부하세요."},
        {id:9,english:"reconcile",korean:"조화시키다",pos:"verb",example:"Reconcile differences.",korExample:"차이를 조화시키세요."},
        {id:10,english:"galvanize",korean:"자극하다",pos:"verb",example:"Galvanize support.",korExample:"지지를 자극하세요."},
        {id:11,english:"epitomize",korean:"전형이다",pos:"verb",example:"Epitomize excellence.",korExample:"우수성의 전형입니다."},
        {id:12,english:"substantive",korean:"실질적인",pos:"adjective",example:"Substantive change.",korExample:"실질적인 변화입니다."},
        {id:13,english:"egregious",korean:"지독한",pos:"adjective",example:"An egregious error.",korExample:"지독한 오류입니다."},
        {id:14,english:"flagrant",korean:"노골적인",pos:"adjective",example:"Flagrant violation.",korExample:"노골적인 위반입니다."},
        {id:15,english:"insidious",korean:"교활한",pos:"adjective",example:"An insidious threat.",korExample:"교활한 위협입니다."},
        {id:16,english:"inveterate",korean:"뿌리 깊은",pos:"adjective",example:"An inveterate habit.",korExample:"뿌리 깊은 습관입니다."},
        {id:17,english:"incorrigible",korean:"교정 불가능한",pos:"adjective",example:"Incorrigible behavior.",korExample:"교정 불가능한 행동입니다."},
        {id:18,english:"recalcitrant",korean:"완강한",pos:"adjective",example:"A recalcitrant attitude.",korExample:"완강한 태도입니다."},
        {id:19,english:"intransigent",korean:"타협하지 않는",pos:"adjective",example:"Intransigent position.",korExample:"타협하지 않는 입장입니다."},
        {id:20,english:"obdurate",korean:"완고한",pos:"adjective",example:"An obdurate refusal.",korExample:"완고한 거부입니다."},
        {id:21,english:"tenuous",korean:"희박한",pos:"adjective",example:"A tenuous connection.",korExample:"희박한 연결입니다."},
        {id:22,english:"perfunctory",korean:"형식적인",pos:"adjective",example:"Perfunctory effort.",korExample:"형식적인 노력입니다."},
        {id:23,english:"desultory",korean:"산만한",pos:"adjective",example:"Desultory conversation.",korExample:"산만한 대화입니다."},
        {id:24,english:"ephemeral",korean:"덧없는",pos:"adjective",example:"Ephemeral beauty.",korExample:"덧없는 아름다움입니다."},
        {id:25,english:"pernicious",korean:"해로운",pos:"adjective",example:"Pernicious influence.",korExample:"해로운 영향입니다."},
        {id:26,english:"inscrutable",korean:"불가해한",pos:"adjective",example:"An inscrutable expression.",korExample:"불가해한 표정입니다."},
        {id:27,english:"audacious",korean:"대담한",pos:"adjective",example:"An audacious plan.",korExample:"대담한 계획입니다."},
        {id:28,english:"proclivity",korean:"성벽",pos:"noun",example:"A proclivity for risk.",korExample:"위험에 대한 성벽입니다."},
        {id:29,english:"propensity",korean:"성향",pos:"noun",example:"A propensity to err.",korExample:"실수하는 성향입니다."},
        {id:30,english:"predilection",korean:"편애",pos:"noun",example:"A predilection for art.",korExample:"예술에 대한 편애입니다."},
        {id:31,english:"antithesis",korean:"정반대",pos:"noun",example:"The antithesis of good.",korExample:"선의 정반대입니다."},
        {id:32,english:"juxtaposition",korean:"병치",pos:"noun",example:"An interesting juxtaposition.",korExample:"흥미로운 병치입니다."},
        {id:33,english:"polarization",korean:"양극화",pos:"noun",example:"Political polarization.",korExample:"정치적 양극화입니다."},
        {id:34,english:"hegemony",korean:"패권",pos:"noun",example:"Cultural hegemony.",korExample:"문화적 패권입니다."},
        {id:35,english:"platitude",korean:"진부한 말",pos:"noun",example:"Empty platitudes.",korExample:"공허한 진부한 말입니다."},
        {id:36,english:"quandary",korean:"곤경",pos:"noun",example:"In a quandary.",korExample:"곤경에 처했습니다."},
        {id:37,english:"conundrum",korean:"난제",pos:"noun",example:"A difficult conundrum.",korExample:"어려운 난제입니다."},
        {id:38,english:"vicissitude",korean:"변천",pos:"noun",example:"Life's vicissitudes.",korExample:"인생의 변천입니다."},
        {id:39,english:"harbinger",korean:"전조",pos:"noun",example:"A harbinger of change.",korExample:"변화의 전조입니다."},
        {id:40,english:"confluence",korean:"합류",pos:"noun",example:"A confluence of events.",korExample:"사건들의 합류입니다."}
    ],

    // ========== Level 6: 35개 (학술논문 기본) ==========
    6: [
    {id:1,english:"alleviate",korean:"완화하다",pos:"verb",example:"Exercise can help alleviate stress.",korExample:"운동은 스트레스를 완화하는 데 도움이 될 수 있습니다."},
    {id:2,english:"ambiguous",korean:"애매한",pos:"adjective",example:"His ambiguous answer confused everyone.",korExample:"그의 애매한 답변은 모두를 혼란스럽게 했습니다."},
    {id:3,english:"articulate",korean:"명확히 표현하다",pos:"verb",example:"She can articulate complex ideas clearly.",korExample:"그녀는 복잡한 생각을 명확히 표현할 수 있습니다."},
    {id:4,english:"compelling",korean:"설득력 있는",pos:"adjective",example:"The lawyer presented a compelling argument.",korExample:"변호사는 설득력 있는 주장을 제시했습니다."},
    {id:5,english:"comprehensive",korean:"포괄적인",pos:"adjective",example:"We need a comprehensive solution to this problem.",korExample:"이 문제에 대한 포괄적인 해결책이 필요합니다."},
    {id:6,english:"consecutive",korean:"연속적인",pos:"adjective",example:"It rained for five consecutive days.",korExample:"5일 연속으로 비가 내렸습니다."},
    {id:7,english:"controversial",korean:"논란의 여지가 있는",pos:"adjective",example:"The politician made a controversial statement.",korExample:"그 정치인은 논란의 여지가 있는 발언을 했습니다."},
    {id:8,english:"crucial",korean:"결정적인",pos:"adjective",example:"This is a crucial moment in our history.",korExample:"이것은 우리 역사에서 결정적인 순간입니다."},
    {id:9,english:"deliberate",korean:"신중한",pos:"adjective",example:"After deliberate consideration, she accepted the offer.",korExample:"신중한 고려 끝에 그녀는 제안을 받아들였습니다."},
    {id:10,english:"diminish",korean:"감소하다",pos:"verb",example:"His influence has diminished over the years.",korExample:"그의 영향력은 세월이 흐르면서 감소했습니다."},
    {id:11,english:"diligent",korean:"부지런한",pos:"adjective",example:"She is a diligent student who studies every day.",korExample:"그녀는 매일 공부하는 부지런한 학생입니다."},
    {id:12,english:"elaborate",korean:"정교한",pos:"adjective",example:"The wedding had elaborate decorations.",korExample:"결혼식에는 정교한 장식이 있었습니다."},
    {id:13,english:"eloquent",korean:"웅변적인",pos:"adjective",example:"The president delivered an eloquent speech.",korExample:"대통령은 웅변적인 연설을 했습니다."},
    {id:14,english:"emphasize",korean:"강조하다",pos:"verb",example:"The teacher emphasized the importance of practice.",korExample:"선생님은 연습의 중요성을 강조했습니다."},
    {id:15,english:"enhance",korean:"향상시키다",pos:"verb",example:"This program will enhance your skills.",korExample:"이 프로그램은 당신의 기술을 향상시킬 것입니다."},
    {id:16,english:"eradicate",korean:"근절하다",pos:"verb",example:"The government is trying to eradicate poverty.",korExample:"정부는 빈곤을 근절하려고 노력하고 있습니다."},
    {id:17,english:"flourish",korean:"번영하다",pos:"verb",example:"The local economy began to flourish.",korExample:"지역 경제가 번영하기 시작했습니다."},
    {id:18,english:"formidable",korean:"만만치 않은",pos:"adjective",example:"They faced a formidable opponent in the finals.",korExample:"그들은 결승전에서 만만치 않은 상대와 맞붙었습니다."},
    {id:19,english:"fundamental",korean:"근본적인",pos:"adjective",example:"Education is a fundamental human right.",korExample:"교육은 근본적인 인권입니다."},
    {id:20,english:"genuine",korean:"진실한",pos:"adjective",example:"She showed genuine concern for his well-being.",korExample:"그녀는 그의 안녕에 대해 진실한 관심을 보였습니다."},
    {id:21,english:"imminent",korean:"임박한",pos:"adjective",example:"The company is facing imminent bankruptcy.",korExample:"그 회사는 임박한 파산에 직면해 있습니다."},
    {id:22,english:"inevitable",korean:"불가피한",pos:"adjective",example:"Change is inevitable in any organization.",korExample:"어떤 조직에서든 변화는 불가피합니다."},
    {id:23,english:"meticulous",korean:"꼼꼼한",pos:"adjective",example:"The scientist conducted meticulous research.",korExample:"그 과학자는 꼼꼼한 연구를 수행했습니다."},
    {id:24,english:"novice",korean:"초보자",pos:"noun",example:"As a novice, he made many mistakes.",korExample:"초보자로서 그는 많은 실수를 했습니다."},
    {id:25,english:"obsolete",korean:"구식의",pos:"adjective",example:"This technology has become obsolete.",korExample:"이 기술은 구식이 되었습니다."},
    {id:26,english:"paramount",korean:"최고의",pos:"adjective",example:"Safety is of paramount importance.",korExample:"안전은 최고의 중요성을 지닙니다."},
    {id:27,english:"persevere",korean:"인내하다",pos:"verb",example:"Despite difficulties, she continued to persevere.",korExample:"어려움에도 불구하고 그녀는 계속 인내했습니다."},
    {id:28,english:"plausible",korean:"그럴듯한",pos:"adjective",example:"He offered a plausible explanation for his absence.",korExample:"그는 자신의 결석에 대해 그럴듯한 설명을 제시했습니다."},
    {id:29,english:"profound",korean:"심오한",pos:"adjective",example:"The book had a profound impact on my life.",korExample:"그 책은 내 인생에 심오한 영향을 미쳤습니다."},
    {id:30,english:"scrutinize",korean:"면밀히 조사하다",pos:"verb",example:"The committee will scrutinize every detail.",korExample:"위원회는 모든 세부 사항을 면밀히 조사할 것입니다."},
    {id:31,english:"substantial",korean:"상당한",pos:"adjective",example:"The project requires substantial funding.",korExample:"이 프로젝트는 상당한 자금이 필요합니다."},
    {id:32,english:"suppress",korean:"억압하다",pos:"verb",example:"The regime tried to suppress dissent.",korExample:"그 정권은 반대 의견을 억압하려고 했습니다."},
    {id:33,english:"tedious",korean:"지루한",pos:"adjective",example:"Data entry can be tedious work.",korExample:"데이터 입력은 지루한 작업일 수 있습니다."},
    {id:34,english:"undermine",korean:"약화시키다",pos:"verb",example:"Negative comments can undermine confidence.",korExample:"부정적인 의견은 자신감을 약화시킬 수 있습니다."},
    {id:35,english:"unprecedented",korean:"전례 없는",pos:"adjective",example:"The country experienced unprecedented economic growth.",korExample:"그 나라는 전례 없는 경제 성장을 경험했습니다."}
],

    // ========== Level 7-20 데이터는 동일한 형식으로 계속... ==========
    // 지면 관계상 Level 7-20은 각각 35-50개씩 추가 필요
    
    7: [
    {id:1,english:"accelerate",korean:"가속화하다",pos:"verb",example:"Technology continues to accelerate social change.",korExample:"기술은 계속해서 사회 변화를 가속화하고 있습니다."},
    {id:2,english:"accumulate",korean:"축적하다",pos:"verb",example:"He managed to accumulate considerable wealth.",korExample:"그는 상당한 부를 축적했습니다."},
    {id:3,english:"adamant",korean:"단호한",pos:"adjective",example:"She was adamant about her decision to resign.",korExample:"그녀는 사임하겠다는 결정에 대해 단호했습니다."},
    {id:4,english:"advocate",korean:"옹호하다",pos:"verb",example:"Many scientists advocate for environmental protection.",korExample:"많은 과학자들이 환경 보호를 옹호합니다."},
    {id:5,english:"aggravate",korean:"악화시키다",pos:"verb",example:"The harsh weather aggravated his condition.",korExample:"혹독한 날씨가 그의 상태를 악화시켰습니다."},
    {id:6,english:"apprehensive",korean:"우려하는",pos:"adjective",example:"Parents are apprehensive about the new policy.",korExample:"학부모들은 새로운 정책에 대해 우려하고 있습니다."},
    {id:7,english:"arbitrary",korean:"임의적인",pos:"adjective",example:"The decision seemed arbitrary and unfair.",korExample:"그 결정은 임의적이고 불공정해 보였습니다."},
    {id:8,english:"ascertain",korean:"확인하다",pos:"verb",example:"We need to ascertain the facts before proceeding.",korExample:"진행하기 전에 사실을 확인해야 합니다."},
    {id:9,english:"astute",korean:"기민한",pos:"adjective",example:"She made an astute observation about the market.",korExample:"그녀는 시장에 대해 기민한 관찰을 했습니다."},
    {id:10,english:"coherent",korean:"일관성 있는",pos:"adjective",example:"He presented a coherent argument.",korExample:"그는 일관성 있는 주장을 제시했습니다."},
    {id:11,english:"commemorate",korean:"기념하다",pos:"verb",example:"The monument commemorates the war heroes.",korExample:"그 기념비는 전쟁 영웅들을 기념합니다."},
    {id:12,english:"compensate",korean:"보상하다",pos:"verb",example:"The company will compensate victims for their losses.",korExample:"회사는 피해자들의 손실을 보상할 것입니다."},
    {id:13,english:"concede",korean:"인정하다",pos:"verb",example:"The candidate conceded defeat gracefully.",korExample:"그 후보는 패배를 기품 있게 인정했습니다."},
    {id:14,english:"condone",korean:"용납하다",pos:"verb",example:"The school does not condone bullying.",korExample:"학교는 괴롭힘을 용납하지 않습니다."},
    {id:15,english:"conspicuous",korean:"눈에 띄는",pos:"adjective",example:"Her absence was conspicuous at the meeting.",korExample:"회의에서 그녀의 부재가 눈에 띄었습니다."},
    {id:16,english:"contemplate",korean:"숙고하다",pos:"verb",example:"She sat quietly to contemplate her future.",korExample:"그녀는 자신의 미래를 숙고하기 위해 조용히 앉아 있었습니다."},
    {id:17,english:"conviction",korean:"확신",pos:"noun",example:"He spoke with strong conviction about his beliefs.",korExample:"그는 자신의 신념에 대해 강한 확신을 가지고 말했습니다."},
    {id:18,english:"deteriorate",korean:"악화되다",pos:"verb",example:"His health began to deteriorate rapidly.",korExample:"그의 건강이 급격히 악화되기 시작했습니다."},
    {id:19,english:"detrimental",korean:"해로운",pos:"adjective",example:"Smoking is detrimental to your health.",korExample:"흡연은 건강에 해롭습니다."},
    {id:20,english:"devise",korean:"고안하다",pos:"verb",example:"Engineers devised a new solution to the problem.",korExample:"엔지니어들이 문제에 대한 새로운 해결책을 고안했습니다."},
    {id:21,english:"discern",korean:"식별하다",pos:"verb",example:"It was difficult to discern the truth from rumors.",korExample:"소문에서 진실을 식별하기는 어려웠습니다."},
    {id:22,english:"disparity",korean:"격차",pos:"noun",example:"There is a huge disparity in income levels.",korExample:"소득 수준에 엄청난 격차가 있습니다."},
    {id:23,english:"doctrine",korean:"교리",pos:"noun",example:"The party adheres to a strict political doctrine.",korExample:"그 정당은 엄격한 정치 교리를 고수합니다."},
    {id:24,english:"dormant",korean:"휴면 상태의",pos:"adjective",example:"The volcano has been dormant for centuries.",korExample:"그 화산은 수세기 동안 휴면 상태였습니다."},
    {id:25,english:"endeavor",korean:"노력하다",pos:"verb",example:"We will endeavor to meet your expectations.",korExample:"우리는 귀하의 기대에 부응하기 위해 노력할 것입니다."},
    {id:26,english:"exacerbate",korean:"악화시키다",pos:"verb",example:"The lack of rain exacerbated the drought.",korExample:"비의 부족이 가뭄을 악화시켰습니다."},
    {id:27,english:"exemplify",korean:"예시하다",pos:"verb",example:"Her dedication exemplifies the team spirit.",korExample:"그녀의 헌신은 팀 정신을 예시합니다."},
    {id:28,english:"expedite",korean:"신속히 처리하다",pos:"verb",example:"We need to expedite the approval process.",korExample:"승인 절차를 신속히 처리해야 합니다."},
    {id:29,english:"facilitate",korean:"촉진하다",pos:"verb",example:"The new system will facilitate communication.",korExample:"새로운 시스템이 의사소통을 촉진할 것입니다."},
    {id:30,english:"feasible",korean:"실현 가능한",pos:"adjective",example:"The plan seems feasible with proper funding.",korExample:"적절한 자금이 있다면 그 계획은 실현 가능해 보입니다."},
    {id:31,english:"fragment",korean:"조각",pos:"noun",example:"Only fragments of the ancient text remain.",korExample:"고대 문헌의 조각만 남아 있습니다."},
    {id:32,english:"gratitude",korean:"감사",pos:"noun",example:"She expressed her gratitude for their support.",korExample:"그녀는 그들의 지원에 대한 감사를 표현했습니다."},
    {id:33,english:"hamper",korean:"방해하다",pos:"verb",example:"Bad weather hampered rescue efforts.",korExample:"악천후가 구조 활동을 방해했습니다."},
    {id:34,english:"hypothetical",korean:"가정적인",pos:"adjective",example:"Let me pose a hypothetical question.",korExample:"가정적인 질문을 하나 제기하겠습니다."},
    {id:35,english:"impede",korean:"저해하다",pos:"verb",example:"Bureaucracy can impede progress.",korExample:"관료주의는 진전을 저해할 수 있습니다."}
],

    8: [
    {id:1,english:"implement",korean:"시행하다",pos:"verb",example:"The government will implement new regulations.",korExample:"정부는 새로운 규정을 시행할 것입니다."},
    {id:2,english:"incentive",korean:"동기",pos:"noun",example:"The bonus serves as an incentive for hard work.",korExample:"보너스는 열심히 일하는 동기가 됩니다."},
    {id:3,english:"inclined",korean:"경향이 있는",pos:"adjective",example:"He is inclined to agree with your proposal.",korExample:"그는 당신의 제안에 동의하는 경향이 있습니다."},
    {id:4,english:"incorporate",korean:"통합하다",pos:"verb",example:"We should incorporate feedback into our plan.",korExample:"우리는 피드백을 계획에 통합해야 합니다."},
    {id:5,english:"indispensable",korean:"필수적인",pos:"adjective",example:"Water is indispensable for human survival.",korExample:"물은 인간 생존에 필수적입니다."},
    {id:6,english:"infer",korean:"추론하다",pos:"verb",example:"From his tone, I could infer his displeasure.",korExample:"그의 어조로부터 나는 그의 불쾌함을 추론할 수 있었습니다."},
    {id:7,english:"inhibit",korean:"억제하다",pos:"verb",example:"Fear can inhibit creativity.",korExample:"두려움은 창의성을 억제할 수 있습니다."},
    {id:8,english:"integrity",korean:"정직성",pos:"noun",example:"She is known for her integrity and honesty.",korExample:"그녀는 정직성과 진실함으로 알려져 있습니다."},
    {id:9,english:"intricate",korean:"복잡한",pos:"adjective",example:"The watch has an intricate mechanism.",korExample:"그 시계는 복잡한 메커니즘을 가지고 있습니다."},
    {id:10,english:"intuitive",korean:"직관적인",pos:"adjective",example:"The app has an intuitive interface.",korExample:"그 앱은 직관적인 인터페이스를 가지고 있습니다."},
    {id:11,english:"jeopardize",korean:"위태롭게 하다",pos:"verb",example:"One mistake could jeopardize the entire project.",korExample:"한 가지 실수가 전체 프로젝트를 위태롭게 할 수 있습니다."},
    {id:12,english:"legitimate",korean:"합법적인",pos:"adjective",example:"She raised a legitimate concern about safety.",korExample:"그녀는 안전에 대한 합법적인 우려를 제기했습니다."},
    {id:13,english:"magnitude",korean:"규모",pos:"noun",example:"The magnitude of the disaster was shocking.",korExample:"재난의 규모는 충격적이었습니다."},
    {id:14,english:"manipulate",korean:"조작하다",pos:"verb",example:"Don't try to manipulate the data.",korExample:"데이터를 조작하려고 하지 마세요."},
    {id:15,english:"mediocre",korean:"평범한",pos:"adjective",example:"The performance was mediocre at best.",korExample:"그 공연은 기껏해야 평범했습니다."},
    {id:16,english:"mitigate",korean:"완화하다",pos:"verb",example:"Measures were taken to mitigate the damage.",korExample:"피해를 완화하기 위한 조치가 취해졌습니다."},
    {id:17,english:"negligible",korean:"무시할 만한",pos:"adjective",example:"The difference in price is negligible.",korExample:"가격 차이는 무시할 만합니다."},
    {id:18,english:"nostalgia",korean:"향수",pos:"noun",example:"The old photos filled her with nostalgia.",korExample:"오래된 사진들이 그녀를 향수로 가득 채웠습니다."},
    {id:19,english:"obscure",korean:"모호한",pos:"adjective",example:"The meaning of the poem is quite obscure.",korExample:"그 시의 의미는 상당히 모호합니다."},
    {id:20,english:"perceive",korean:"인식하다",pos:"verb",example:"How do you perceive the current situation?",korExample:"현재 상황을 어떻게 인식하십니까?"},
    {id:21,english:"perspective",korean:"관점",pos:"noun",example:"We need to see things from a different perspective.",korExample:"우리는 다른 관점에서 사물을 볼 필요가 있습니다."},
    {id:22,english:"persuasive",korean:"설득력 있는",pos:"adjective",example:"She delivered a persuasive presentation.",korExample:"그녀는 설득력 있는 발표를 했습니다."},
    {id:23,english:"pertinent",korean:"적절한",pos:"adjective",example:"He asked a pertinent question.",korExample:"그는 적절한 질문을 했습니다."},
    {id:24,english:"prevalent",korean:"만연한",pos:"adjective",example:"Stress is prevalent in modern society.",korExample:"스트레스는 현대 사회에 만연해 있습니다."},
    {id:25,english:"procrastinate",korean:"미루다",pos:"verb",example:"Don't procrastinate on important tasks.",korExample:"중요한 일을 미루지 마세요."},
    {id:26,english:"prudent",korean:"신중한",pos:"adjective",example:"It would be prudent to save money.",korExample:"돈을 저축하는 것이 신중할 것입니다."},
    {id:27,english:"reciprocal",korean:"상호적인",pos:"adjective",example:"Trust requires reciprocal respect.",korExample:"신뢰는 상호적인 존중을 필요로 합니다."},
    {id:28,english:"refute",korean:"반박하다",pos:"verb",example:"The scientist refuted the theory with evidence.",korExample:"그 과학자는 증거로 그 이론을 반박했습니다."},
    {id:29,english:"reluctant",korean:"꺼리는",pos:"adjective",example:"He was reluctant to accept the offer.",korExample:"그는 그 제안을 받아들이기를 꺼렸습니다."},
    {id:30,english:"resilient",korean:"회복력 있는",pos:"adjective",example:"Children are remarkably resilient.",korExample:"아이들은 놀랍도록 회복력이 있습니다."},
    {id:31,english:"rigorous",korean:"엄격한",pos:"adjective",example:"The training program is very rigorous.",korExample:"그 훈련 프로그램은 매우 엄격합니다."},
    {id:32,english:"skeptical",korean:"회의적인",pos:"adjective",example:"Many people are skeptical about the plan.",korExample:"많은 사람들이 그 계획에 대해 회의적입니다."},
    {id:33,english:"stagnant",korean:"정체된",pos:"adjective",example:"The economy has been stagnant for years.",korExample:"경제는 수년간 정체되어 있습니다."},
    {id:34,english:"stimulus",korean:"자극",pos:"noun",example:"The government provided economic stimulus.",korExample:"정부는 경제 자극을 제공했습니다."},
    {id:35,english:"superficial",korean:"피상적인",pos:"adjective",example:"His knowledge of the subject is superficial.",korExample:"그 주제에 대한 그의 지식은 피상적입니다."}
],
9: [
    {id:1,english:"sustain",korean:"유지하다",pos:"verb",example:"We need to sustain economic growth.",korExample:"우리는 경제 성장을 유지해야 합니다."},
    {id:2,english:"tangible",korean:"실질적인",pos:"adjective",example:"The project has produced tangible results.",korExample:"그 프로젝트는 실질적인 결과를 만들어냈습니다."},
    {id:3,english:"tentative",korean:"잠정적인",pos:"adjective",example:"We made a tentative agreement.",korExample:"우리는 잠정적인 합의를 했습니다."},
    {id:4,english:"thrive",korean:"번창하다",pos:"verb",example:"Small businesses can thrive in this area.",korExample:"소규모 사업체들이 이 지역에서 번창할 수 있습니다."},
    {id:5,english:"tolerate",korean:"견디다",pos:"verb",example:"She cannot tolerate dishonesty.",korExample:"그녀는 부정직함을 견딜 수 없습니다."},
    {id:6,english:"transparent",korean:"투명한",pos:"adjective",example:"The government should be transparent in its dealings.",korExample:"정부는 업무 처리에 있어 투명해야 합니다."},
    {id:7,english:"trivial",korean:"사소한",pos:"adjective",example:"Don't waste time on trivial matters.",korExample:"사소한 문제에 시간을 낭비하지 마세요."},
    {id:8,english:"turbulent",korean:"격동의",pos:"adjective",example:"The country went through a turbulent period.",korExample:"그 나라는 격동의 시기를 겪었습니다."},
    {id:9,english:"unanimous",korean:"만장일치의",pos:"adjective",example:"The decision was unanimous.",korExample:"그 결정은 만장일치였습니다."},
    {id:10,english:"undertake",korean:"착수하다",pos:"verb",example:"The team will undertake a new project.",korExample:"팀은 새로운 프로젝트에 착수할 것입니다."},
    {id:11,english:"utilize",korean:"활용하다",pos:"verb",example:"We should utilize available resources efficiently.",korExample:"우리는 이용 가능한 자원을 효율적으로 활용해야 합니다."},
    {id:12,english:"verify",korean:"검증하다",pos:"verb",example:"Please verify your identity.",korExample:"신원을 검증해 주세요."},
    {id:13,english:"viable",korean:"실행 가능한",pos:"adjective",example:"Is this a viable alternative?",korExample:"이것이 실행 가능한 대안입니까?"},
    {id:14,english:"vigorous",korean:"활기찬",pos:"adjective",example:"He engaged in vigorous exercise.",korExample:"그는 활기찬 운동을 했습니다."},
    {id:15,english:"virtue",korean:"미덕",pos:"noun",example:"Patience is a virtue.",korExample:"인내는 미덕입니다."},
    {id:16,english:"volatile",korean:"변덕스러운",pos:"adjective",example:"The stock market is very volatile.",korExample:"주식 시장은 매우 변덕스럽습니다."},
    {id:17,english:"vulnerable",korean:"취약한",pos:"adjective",example:"Children are vulnerable to diseases.",korExample:"아이들은 질병에 취약합니다."},
    {id:18,english:"warrant",korean:"정당화하다",pos:"verb",example:"The situation does not warrant such drastic action.",korExample:"그 상황은 그러한 과감한 조치를 정당화하지 못합니다."},
    {id:19,english:"withdraw",korean:"철회하다",pos:"verb",example:"He decided to withdraw his proposal.",korExample:"그는 자신의 제안을 철회하기로 결정했습니다."},
    {id:20,english:"abolish",korean:"폐지하다",pos:"verb",example:"The law was abolished last year.",korExample:"그 법은 작년에 폐지되었습니다."},
    {id:21,english:"absurd",korean:"터무니없는",pos:"adjective",example:"The accusation is completely absurd.",korExample:"그 비난은 완전히 터무니없습니다."},
    {id:22,english:"accompany",korean:"동반하다",pos:"verb",example:"I will accompany you to the meeting.",korExample:"회의에 당신과 동반하겠습니다."},
    {id:23,english:"acknowledge",korean:"인정하다",pos:"verb",example:"He acknowledged his mistake.",korExample:"그는 자신의 실수를 인정했습니다."},
    {id:24,english:"adhere",korean:"고수하다",pos:"verb",example:"We must adhere to the regulations.",korExample:"우리는 규정을 고수해야 합니다."},
    {id:25,english:"adjacent",korean:"인접한",pos:"adjective",example:"The hotel is adjacent to the station.",korExample:"호텔은 역에 인접해 있습니다."},
    {id:26,english:"ambition",korean:"야망",pos:"noun",example:"She has great ambition to succeed.",korExample:"그녀는 성공하려는 큰 야망이 있습니다."},
    {id:27,english:"ample",korean:"충분한",pos:"adjective",example:"There is ample time to finish the work.",korExample:"작업을 끝낼 충분한 시간이 있습니다."},
    {id:28,english:"analogy",korean:"유추",pos:"noun",example:"He explained the concept using an analogy.",korExample:"그는 유추를 사용하여 개념을 설명했습니다."},
    {id:29,english:"anonymous",korean:"익명의",pos:"adjective",example:"The donor wished to remain anonymous.",korExample:"기부자는 익명으로 남기를 원했습니다."},
    {id:30,english:"anticipate",korean:"예상하다",pos:"verb",example:"We anticipate strong opposition.",korExample:"우리는 강한 반대를 예상합니다."},
    {id:31,english:"apparent",korean:"명백한",pos:"adjective",example:"It was apparent that he was lying.",korExample:"그가 거짓말하고 있다는 것은 명백했습니다."},
    {id:32,english:"aspire",korean:"열망하다",pos:"verb",example:"Many students aspire to become doctors.",korExample:"많은 학생들이 의사가 되기를 열망합니다."},
    {id:33,english:"assimilate",korean:"흡수하다",pos:"verb",example:"Immigrants gradually assimilate into society.",korExample:"이민자들은 점차 사회에 흡수됩니다."},
    {id:34,english:"attain",korean:"달성하다",pos:"verb",example:"She worked hard to attain her goal.",korExample:"그녀는 목표를 달성하기 위해 열심히 일했습니다."},
    {id:35,english:"authentic",korean:"진정한",pos:"adjective",example:"This is an authentic piece of art.",korExample:"이것은 진정한 예술 작품입니다."}
],

10: [
    {id:1,english:"benign",korean:"온화한",pos:"adjective",example:"The tumor turned out to be benign.",korExample:"종양은 양성인 것으로 밝혀졌습니다."},
    {id:2,english:"bias",korean:"편견",pos:"noun",example:"We must eliminate bias from our decisions.",korExample:"우리는 결정에서 편견을 제거해야 합니다."},
    {id:3,english:"brevity",korean:"간결함",pos:"noun",example:"Brevity is important in business communication.",korExample:"간결함은 비즈니스 커뮤니케이션에서 중요합니다."},
    {id:4,english:"candid",korean:"솔직한",pos:"adjective",example:"I appreciate your candid opinion.",korExample:"당신의 솔직한 의견에 감사드립니다."},
    {id:5,english:"cease",korean:"중단하다",pos:"verb",example:"The fighting ceased at midnight.",korExample:"전투는 자정에 중단되었습니다."},
    {id:6,english:"chronological",korean:"연대순의",pos:"adjective",example:"Please arrange the events in chronological order.",korExample:"사건들을 연대순으로 정리해 주세요."},
    {id:7,english:"circumvent",korean:"우회하다",pos:"verb",example:"They tried to circumvent the regulations.",korExample:"그들은 규정을 우회하려고 했습니다."},
    {id:8,english:"clarify",korean:"명확히 하다",pos:"verb",example:"Could you clarify your position?",korExample:"당신의 입장을 명확히 해 주시겠습니까?"},
    {id:9,english:"coerce",korean:"강요하다",pos:"verb",example:"No one should coerce you into making a decision.",korExample:"누구도 당신에게 결정을 강요해서는 안 됩니다."},
    {id:10,english:"collaborate",korean:"협력하다",pos:"verb",example:"The two companies will collaborate on the project.",korExample:"두 회사는 프로젝트에서 협력할 것입니다."},
    {id:11,english:"commence",korean:"시작하다",pos:"verb",example:"The ceremony will commence at noon.",korExample:"행사는 정오에 시작될 것입니다."},
    {id:12,english:"compatible",korean:"양립 가능한",pos:"adjective",example:"These two systems are not compatible.",korExample:"이 두 시스템은 양립 가능하지 않습니다."},
    {id:13,english:"complacent",korean:"안주하는",pos:"adjective",example:"We must not become complacent about our success.",korExample:"우리는 성공에 안주해서는 안 됩니다."},
    {id:14,english:"comply",korean:"준수하다",pos:"verb",example:"All employees must comply with company policies.",korExample:"모든 직원은 회사 정책을 준수해야 합니다."},
    {id:15,english:"concise",korean:"간결한",pos:"adjective",example:"Please provide a concise summary.",korExample:"간결한 요약을 제공해 주세요."},
    {id:16,english:"concurrent",korean:"동시의",pos:"adjective",example:"He is taking three concurrent courses.",korExample:"그는 세 개의 동시 과정을 듣고 있습니다."},
    {id:17,english:"condemn",korean:"비난하다",pos:"verb",example:"The international community condemned the attack.",korExample:"국제 사회는 그 공격을 비난했습니다."},
    {id:18,english:"confidential",korean:"기밀의",pos:"adjective",example:"This information is strictly confidential.",korExample:"이 정보는 엄격히 기밀입니다."},
    {id:19,english:"confine",korean:"제한하다",pos:"verb",example:"Please confine your comments to the main topic.",korExample:"주요 주제로 의견을 제한해 주세요."},
    {id:20,english:"confront",korean:"직면하다",pos:"verb",example:"We must confront this problem directly.",korExample:"우리는 이 문제에 직접 직면해야 합니다."},
    {id:21,english:"conscientious",korean:"양심적인",pos:"adjective",example:"He is a conscientious worker.",korExample:"그는 양심적인 근로자입니다."},
    {id:22,english:"consensus",korean:"합의",pos:"noun",example:"We reached a consensus after long discussions.",korExample:"긴 논의 끝에 우리는 합의에 도달했습니다."},
    {id:23,english:"constrain",korean:"제약하다",pos:"verb",example:"Budget limitations constrain our options.",korExample:"예산 제한이 우리의 선택을 제약합니다."},
    {id:24,english:"contempt",korean:"경멸",pos:"noun",example:"He showed contempt for the rules.",korExample:"그는 규칙에 대한 경멸을 보였습니다."},
    {id:25,english:"contradict",korean:"모순되다",pos:"verb",example:"Your actions contradict your words.",korExample:"당신의 행동은 말과 모순됩니다."},
    {id:26,english:"convene",korean:"소집하다",pos:"verb",example:"The committee will convene next week.",korExample:"위원회는 다음 주에 소집될 것입니다."},
    {id:27,english:"converge",korean:"모이다",pos:"verb",example:"Several roads converge at this point.",korExample:"여러 도로가 이 지점에서 모입니다."},
    {id:28,english:"credible",korean:"신빙성 있는",pos:"adjective",example:"The witness provided credible testimony.",korExample:"증인은 신빙성 있는 증언을 제공했습니다."},
    {id:29,english:"criterion",korean:"기준",pos:"noun",example:"What is the main criterion for selection?",korExample:"선발의 주요 기준은 무엇입니까?"},
    {id:30,english:"culminate",korean:"절정에 이르다",pos:"verb",example:"The festival will culminate in a grand parade.",korExample:"축제는 성대한 퍼레이드로 절정에 이를 것입니다."},
    {id:31,english:"curtail",korean:"단축하다",pos:"verb",example:"The company had to curtail spending.",korExample:"회사는 지출을 단축해야 했습니다."},
    {id:32,english:"deceive",korean:"속이다",pos:"verb",example:"He tried to deceive the investigators.",korExample:"그는 조사관들을 속이려고 했습니다."},
    {id:33,english:"decipher",korean:"해독하다",pos:"verb",example:"Scientists are trying to decipher the ancient text.",korExample:"과학자들은 고대 문헌을 해독하려고 노력하고 있습니다."},
    {id:34,english:"dedicate",korean:"헌신하다",pos:"verb",example:"She dedicated her life to helping others.",korExample:"그녀는 다른 사람들을 돕는 데 인생을 헌신했습니다."},
    {id:35,english:"deem",korean:"간주하다",pos:"verb",example:"The court deemed the evidence insufficient.",korExample:"법원은 증거가 불충분하다고 간주했습니다."}
],
11: [
    {id:1,english:"acquiesce",korean:"묵인하다",pos:"verb",example:"He reluctantly acquiesced to their demands.",korExample:"그는 마지못해 그들의 요구를 묵인했습니다."},
    {id:2,english:"acrimonious",korean:"신랄한",pos:"adjective",example:"The divorce proceedings were acrimonious.",korExample:"이혼 절차는 신랄했습니다."},
    {id:3,english:"adjudicate",korean:"판결하다",pos:"verb",example:"The court will adjudicate the dispute.",korExample:"법원이 그 분쟁을 판결할 것입니다."},
    {id:4,english:"admonish",korean:"훈계하다",pos:"verb",example:"The teacher admonished the student for cheating.",korExample:"교사는 부정행위를 한 학생을 훈계했습니다."},
    {id:5,english:"adversary",korean:"적수",pos:"noun",example:"He faced a formidable adversary in the final.",korExample:"그는 결승전에서 만만치 않은 적수와 맞붙었습니다."},
    {id:6,english:"aesthetic",korean:"미학적인",pos:"adjective",example:"The building has great aesthetic appeal.",korExample:"그 건물은 훌륭한 미학적 매력이 있습니다."},
    {id:7,english:"affinity",korean:"친화력",pos:"noun",example:"She has a natural affinity for languages.",korExample:"그녀는 언어에 대한 타고난 친화력이 있습니다."},
    {id:8,english:"affluent",korean:"부유한",pos:"adjective",example:"They live in an affluent neighborhood.",korExample:"그들은 부유한 동네에 살고 있습니다."},
    {id:9,english:"alacrity",korean:"민첩함",pos:"noun",example:"He accepted the offer with alacrity.",korExample:"그는 민첩하게 제안을 받아들였습니다."},
    {id:10,english:"albeit",korean:"비록 ~이지만",pos:"conjunction",example:"The plan is risky, albeit potentially profitable.",korExample:"그 계획은 비록 잠재적으로 수익성이 있지만 위험합니다."},
    {id:11,english:"allegation",korean:"혐의",pos:"noun",example:"He denied all allegations of misconduct.",korExample:"그는 모든 부정행위 혐의를 부인했습니다."},
    {id:12,english:"allude",korean:"암시하다",pos:"verb",example:"She alluded to problems in their relationship.",korExample:"그녀는 그들의 관계에서의 문제를 암시했습니다."},
    {id:13,english:"amalgamate",korean:"합병하다",pos:"verb",example:"The two firms decided to amalgamate.",korExample:"두 회사는 합병하기로 결정했습니다."},
    {id:14,english:"ambivalent",korean:"양면적인",pos:"adjective",example:"She felt ambivalent about the job offer.",korExample:"그녀는 일자리 제안에 대해 양면적인 감정을 느꼈습니다."},
    {id:15,english:"ameliorate",korean:"개선하다",pos:"verb",example:"New policies aim to ameliorate living conditions.",korExample:"새로운 정책은 생활 여건을 개선하는 것을 목표로 합니다."},
    {id:16,english:"anachronism",korean:"시대착오",pos:"noun",example:"That law is an anachronism in modern society.",korExample:"그 법은 현대 사회에서 시대착오입니다."},
    {id:17,english:"analogous",korean:"유사한",pos:"adjective",example:"The situation is analogous to what happened in 2008.",korExample:"그 상황은 2008년에 일어난 일과 유사합니다."},
    {id:18,english:"animosity",korean:"적의",pos:"noun",example:"There was deep animosity between the rivals.",korExample:"경쟁자들 사이에는 깊은 적의가 있었습니다."},
    {id:19,english:"anomaly",korean:"이례",pos:"noun",example:"The test results show a strange anomaly.",korExample:"검사 결과는 이상한 이례를 보여줍니다."},
    {id:20,english:"antipathy",korean:"반감",pos:"noun",example:"He felt a strong antipathy toward the regime.",korExample:"그는 그 정권에 대한 강한 반감을 느꼈습니다."},
    {id:21,english:"apathy",korean:"무관심",pos:"noun",example:"Voter apathy is a serious problem.",korExample:"유권자 무관심은 심각한 문제입니다."},
    {id:22,english:"appease",korean:"달래다",pos:"verb",example:"The government tried to appease protesters.",korExample:"정부는 시위자들을 달래려고 했습니다."},
    {id:23,english:"aptitude",korean:"적성",pos:"noun",example:"She has a remarkable aptitude for mathematics.",korExample:"그녀는 수학에 대한 뛰어난 적성이 있습니다."},
    {id:24,english:"arbitrary",korean:"자의적인",pos:"adjective",example:"The ruler made arbitrary decisions.",korExample:"통치자는 자의적인 결정을 내렸습니다."},
    {id:25,english:"arduous",korean:"힘든",pos:"adjective",example:"The climb was long and arduous.",korExample:"그 등반은 길고 힘들었습니다."},
    {id:26,english:"articulation",korean:"표현",pos:"noun",example:"His articulation of the problem was clear.",korExample:"문제에 대한 그의 표현은 명확했습니다."},
    {id:27,english:"ascribe",korean:"귀속시키다",pos:"verb",example:"We cannot ascribe the failure to one cause.",korExample:"우리는 실패를 한 가지 원인에 귀속시킬 수 없습니다."},
    {id:28,english:"assiduous",korean:"근면한",pos:"adjective",example:"She is an assiduous researcher.",korExample:"그녀는 근면한 연구자입니다."},
    {id:29,english:"assuage",korean:"진정시키다",pos:"verb",example:"Nothing could assuage his guilt.",korExample:"어떤 것도 그의 죄책감을 진정시킬 수 없었습니다."},
    {id:30,english:"audacious",korean:"대담한",pos:"adjective",example:"It was an audacious plan.",korExample:"그것은 대담한 계획이었습니다."},
    {id:31,english:"augment",korean:"증대시키다",pos:"verb",example:"We need to augment our workforce.",korExample:"우리는 인력을 증대시켜야 합니다."},
    {id:32,english:"auspicious",korean:"길조의",pos:"adjective",example:"It was an auspicious beginning.",korExample:"그것은 길조의 시작이었습니다."},
    {id:33,english:"austere",korean:"엄격한",pos:"adjective",example:"He lived an austere life.",korExample:"그는 엄격한 삶을 살았습니다."},
    {id:34,english:"authoritarian",korean:"권위주의적인",pos:"adjective",example:"The regime became increasingly authoritarian.",korExample:"그 정권은 점점 더 권위주의적이 되었습니다."},
    {id:35,english:"avarice",korean:"탐욕",pos:"noun",example:"His avarice led to his downfall.",korExample:"그의 탐욕이 그의 몰락을 초래했습니다."}
],
12: [
    {id:1,english:"banal",korean:"진부한",pos:"adjective",example:"The movie's plot was utterly banal.",korExample:"그 영화의 줄거리는 완전히 진부했습니다."},
    {id:2,english:"bellicose",korean:"호전적인",pos:"adjective",example:"His bellicose rhetoric alarmed neighboring countries.",korExample:"그의 호전적인 수사는 이웃 나라들을 경악시켰습니다."},
    {id:3,english:"benevolent",korean:"자비로운",pos:"adjective",example:"She was known for her benevolent nature.",korExample:"그녀는 자비로운 성품으로 알려져 있었습니다."},
    {id:4,english:"bolster",korean:"강화하다",pos:"verb",example:"The evidence will bolster their case.",korExample:"증거는 그들의 주장을 강화할 것입니다."},
    {id:5,english:"boon",korean:"혜택",pos:"noun",example:"The new technology is a boon for farmers.",korExample:"새로운 기술은 농부들에게 혜택입니다."},
    {id:6,english:"bureaucracy",korean:"관료제",pos:"noun",example:"The bureaucracy slows down decision-making.",korExample:"관료제는 의사 결정을 늦춥니다."},
    {id:7,english:"burgeon",korean:"급증하다",pos:"verb",example:"The city's population began to burgeon.",korExample:"도시의 인구가 급증하기 시작했습니다."},
    {id:8,english:"callous",korean:"냉담한",pos:"adjective",example:"His callous attitude shocked everyone.",korExample:"그의 냉담한 태도는 모두를 충격에 빠뜨렸습니다."},
    {id:9,english:"candor",korean:"솔직함",pos:"noun",example:"I appreciate your candor in this matter.",korExample:"이 문제에 대한 당신의 솔직함에 감사드립니다."},
    {id:10,english:"capitulate",korean:"항복하다",pos:"verb",example:"The rebels refused to capitulate.",korExample:"반군은 항복하기를 거부했습니다."},
    {id:11,english:"capricious",korean:"변덕스러운",pos:"adjective",example:"The weather here is notoriously capricious.",korExample:"이곳의 날씨는 악명 높게 변덕스럽습니다."},
    {id:12,english:"castigate",korean:"호되게 꾸짖다",pos:"verb",example:"The press castigated the minister for his remarks.",korExample:"언론은 장관의 발언에 대해 호되게 꾸짖었습니다."},
    {id:13,english:"catalyst",korean:"촉매",pos:"noun",example:"The crisis became a catalyst for reform.",korExample:"위기는 개혁의 촉매가 되었습니다."},
    {id:14,english:"caustic",korean:"신랄한",pos:"adjective",example:"His caustic comments hurt her feelings.",korExample:"그의 신랄한 논평은 그녀의 감정을 상하게 했습니다."},
    {id:15,english:"censor",korean:"검열하다",pos:"verb",example:"The government tried to censor the press.",korExample:"정부는 언론을 검열하려고 했습니다."},
    {id:16,english:"chagrin",korean:"분함",pos:"noun",example:"To his chagrin, he failed the exam.",korExample:"그가 분함을 느낀 것은 시험에 떨어졌기 때문입니다."},
    {id:17,english:"charlatan",korean:"사기꾼",pos:"noun",example:"The supposed expert was exposed as a charlatan.",korExample:"그 자칭 전문가는 사기꾼으로 밝혀졌습니다."},
    {id:18,english:"circumspect",korean:"신중한",pos:"adjective",example:"She was circumspect in her response.",korExample:"그녀는 대응에 있어 신중했습니다."},
    {id:19,english:"clandestine",korean:"은밀한",pos:"adjective",example:"They held clandestine meetings.",korExample:"그들은 은밀한 회의를 가졌습니다."},
    {id:20,english:"clemency",korean:"관용",pos:"noun",example:"The prisoner appealed for clemency.",korExample:"수감자는 관용을 호소했습니다."},
    {id:21,english:"coalesce",korean:"합체하다",pos:"verb",example:"Various groups coalesced to form a coalition.",korExample:"여러 집단이 합체하여 연합을 형성했습니다."},
    {id:22,english:"cogent",korean:"설득력 있는",pos:"adjective",example:"She presented a cogent argument.",korExample:"그녀는 설득력 있는 논거를 제시했습니다."},
    {id:23,english:"cognizant",korean:"인식하는",pos:"adjective",example:"We are cognizant of the challenges ahead.",korExample:"우리는 앞으로의 도전을 인식하고 있습니다."},
    {id:24,english:"collusion",korean:"공모",pos:"noun",example:"There was evidence of collusion between companies.",korExample:"회사들 간의 공모 증거가 있었습니다."},
    {id:25,english:"commensurate",korean:"상응하는",pos:"adjective",example:"The salary is commensurate with experience.",korExample:"급여는 경험에 상응합니다."},
    {id:26,english:"compel",korean:"강제하다",pos:"verb",example:"The evidence compelled him to confess.",korExample:"증거가 그를 자백하도록 강제했습니다."},
    {id:27,english:"compendium",korean:"개요",pos:"noun",example:"The book is a compendium of folk tales.",korExample:"그 책은 민담의 개요입니다."},
    {id:28,english:"complacency",korean:"자기만족",pos:"noun",example:"Complacency can lead to failure.",korExample:"자기만족은 실패로 이어질 수 있습니다."},
    {id:29,english:"conciliatory",korean:"유화적인",pos:"adjective",example:"He adopted a conciliatory tone.",korExample:"그는 유화적인 어조를 취했습니다."},
    {id:30,english:"concoct",korean:"조작하다",pos:"verb",example:"He concocted an elaborate excuse.",korExample:"그는 정교한 변명을 조작했습니다."},
    {id:31,english:"congenial",korean:"마음에 드는",pos:"adjective",example:"The working environment is congenial.",korExample:"근무 환경은 마음에 듭니다."},
    {id:32,english:"conjecture",korean:"추측",pos:"noun",example:"Without evidence, it's mere conjecture.",korExample:"증거 없이는 그것은 단지 추측일 뿐입니다."},
    {id:33,english:"connive",korean:"묵인하다",pos:"verb",example:"Officials connived at the illegal activity.",korExample:"공무원들은 불법 활동을 묵인했습니다."},
    {id:34,english:"conscript",korean:"징집하다",pos:"verb",example:"Young men were conscripted into the army.",korExample:"젊은이들이 군대에 징집되었습니다."},
    {id:35,english:"conspire",korean:"공모하다",pos:"verb",example:"They conspired to overthrow the government.",korExample:"그들은 정부를 전복시키기 위해 공모했습니다."}
],

13: [
    {id:1,english:"construe",korean:"해석하다",pos:"verb",example:"His silence could be construed as agreement.",korExample:"그의 침묵은 동의로 해석될 수 있습니다."},
    {id:2,english:"contentious",korean:"논쟁적인",pos:"adjective",example:"The proposal raised contentious issues.",korExample:"그 제안은 논쟁적인 쟁점을 제기했습니다."},
    {id:3,english:"contrition",korean:"뉘우침",pos:"noun",example:"He showed genuine contrition for his actions.",korExample:"그는 자신의 행동에 대해 진정한 뉘우침을 보였습니다."},
    {id:4,english:"contrive",korean:"고안하다",pos:"verb",example:"She contrived a solution to the problem.",korExample:"그녀는 문제에 대한 해결책을 고안했습니다."},
    {id:5,english:"conundrum",korean:"난제",pos:"noun",example:"The situation presents a moral conundrum.",korExample:"그 상황은 도덕적 난제를 제시합니다."},
    {id:6,english:"convivial",korean:"유쾌한",pos:"adjective",example:"The dinner party had a convivial atmosphere.",korExample:"만찬회는 유쾌한 분위기였습니다."},
    {id:7,english:"copious",korean:"풍부한",pos:"adjective",example:"She took copious notes during the lecture.",korExample:"그녀는 강의 중에 풍부한 메모를 했습니다."},
    {id:8,english:"corroborate",korean:"확증하다",pos:"verb",example:"The witness corroborated his testimony.",korExample:"증인이 그의 증언을 확증했습니다."},
    {id:9,english:"countenance",korean:"용납하다",pos:"verb",example:"The school will not countenance such behavior.",korExample:"학교는 그러한 행동을 용납하지 않을 것입니다."},
    {id:10,english:"covert",korean:"은밀한",pos:"adjective",example:"The agents conducted covert operations.",korExample:"요원들은 은밀한 작전을 수행했습니다."},
    {id:11,english:"craven",korean:"비겁한",pos:"adjective",example:"His craven retreat disappointed his supporters.",korExample:"그의 비겁한 후퇴는 지지자들을 실망시켰습니다."},
    {id:12,english:"credulous",korean:"잘 믿는",pos:"adjective",example:"Only the most credulous would believe that story.",korExample:"가장 잘 믿는 사람만이 그 이야기를 믿을 것입니다."},
    {id:13,english:"culpable",korean:"비난받을 만한",pos:"adjective",example:"He was found culpable for the accident.",korExample:"그는 사고에 대해 비난받을 만하다고 판명되었습니다."},
    {id:14,english:"cursory",korean:"대충 훑어보는",pos:"adjective",example:"He gave the report only a cursory glance.",korExample:"그는 보고서를 대충 훑어보기만 했습니다."},
    {id:15,english:"cynical",korean:"냉소적인",pos:"adjective",example:"She has become cynical about politics.",korExample:"그녀는 정치에 대해 냉소적이 되었습니다."},
    {id:16,english:"dearth",korean:"부족",pos:"noun",example:"There is a dearth of qualified candidates.",korExample:"자격을 갖춘 후보자의 부족이 있습니다."},
    {id:17,english:"debacle",korean:"대실패",pos:"noun",example:"The project ended in a complete debacle.",korExample:"그 프로젝트는 완전한 대실패로 끝났습니다."},
    {id:18,english:"debase",korean:"격하시키다",pos:"verb",example:"The scandal debased the institution's reputation.",korExample:"그 스캔들은 기관의 명성을 격하시켰습니다."},
    {id:19,english:"debilitate",korean:"약화시키다",pos:"verb",example:"The disease can severely debilitate patients.",korExample:"그 질병은 환자들을 심각하게 약화시킬 수 있습니다."},
    {id:20,english:"decorum",korean:"예의",pos:"noun",example:"Guests are expected to observe proper decorum.",korExample:"손님들은 적절한 예의를 지킬 것으로 기대됩니다."},
    {id:21,english:"decry",korean:"공개적으로 비난하다",pos:"verb",example:"Critics decried the new legislation.",korExample:"비평가들은 새로운 법안을 공개적으로 비난했습니다."},
    {id:22,english:"deference",korean:"존중",pos:"noun",example:"He showed deference to his elders.",korExample:"그는 어른들에게 존중을 보였습니다."},
    {id:23,english:"delineate",korean:"윤곽을 그리다",pos:"verb",example:"The report clearly delineates the problems.",korExample:"보고서는 문제들의 윤곽을 명확히 그립니다."},
    {id:24,english:"demeanor",korean:"태도",pos:"noun",example:"His calm demeanor reassured the team.",korExample:"그의 차분한 태도는 팀을 안심시켰습니다."},
    {id:25,english:"denounce",korean:"규탄하다",pos:"verb",example:"The opposition denounced the government's policy.",korExample:"야당은 정부의 정책을 규탄했습니다."},
    {id:26,english:"deplete",korean:"고갈시키다",pos:"verb",example:"Overuse will deplete natural resources.",korExample:"과도한 사용은 천연자원을 고갈시킬 것입니다."},
    {id:27,english:"deplore",korean:"개탄하다",pos:"verb",example:"We deplore the violence that occurred.",korExample:"우리는 발생한 폭력을 개탄합니다."},
    {id:28,english:"depravity",korean:"타락",pos:"noun",example:"The crime revealed shocking depravity.",korExample:"그 범죄는 충격적인 타락을 드러냈습니다."},
    {id:29,english:"deride",korean:"조롱하다",pos:"verb",example:"Critics derided his ambitious plans.",korExample:"비평가들은 그의 야심찬 계획을 조롱했습니다."},
    {id:30,english:"derivative",korean:"파생된",pos:"adjective",example:"His work is derivative and lacks originality.",korExample:"그의 작품은 파생되었고 독창성이 부족합니다."},
    {id:31,english:"despondent",korean:"낙담한",pos:"adjective",example:"She felt despondent after losing the election.",korExample:"그녀는 선거에서 진 후 낙담했습니다."},
    {id:32,english:"despot",korean:"독재자",pos:"noun",example:"The country suffered under a brutal despot.",korExample:"그 나라는 잔혹한 독재자 아래에서 고통받았습니다."},
    {id:33,english:"destitute",korean:"극빈한",pos:"adjective",example:"The war left many families destitute.",korExample:"전쟁은 많은 가족을 극빈하게 만들었습니다."},
    {id:34,english:"deter",korean:"단념시키다",pos:"verb",example:"Harsh penalties deter potential offenders.",korExample:"가혹한 처벌은 잠재적 범죄자를 단념시킵니다."},
    {id:35,english:"detract",korean:"손상시키다",pos:"verb",example:"Minor flaws do not detract from its overall quality.",korExample:"사소한 결함은 전체적인 품질을 손상시키지 않습니다."}
],
14: [
    {id:1,english:"devoid",korean:"결여된",pos:"adjective",example:"His speech was devoid of substance.",korExample:"그의 연설은 내용이 결여되어 있었습니다."},
    {id:2,english:"dexterous",korean:"능숙한",pos:"adjective",example:"The surgeon's dexterous hands saved lives.",korExample:"외과 의사의 능숙한 손은 생명을 구했습니다."},
    {id:3,english:"didactic",korean:"교훈적인",pos:"adjective",example:"The novel has a didactic purpose.",korExample:"그 소설은 교훈적인 목적이 있습니다."},
    {id:4,english:"diffident",korean:"자신 없는",pos:"adjective",example:"She was diffident about expressing her opinions.",korExample:"그녀는 자신의 의견을 표현하는 데 자신이 없었습니다."},
    {id:5,english:"digress",korean:"벗어나다",pos:"verb",example:"I apologize for digressing from the main topic.",korExample:"주제에서 벗어난 점 사과드립니다."},
    {id:6,english:"dilate",korean:"확대하다",pos:"verb",example:"Her pupils dilated in the darkness.",korExample:"그녀의 동공이 어둠 속에서 확대되었습니다."},
    {id:7,english:"diligence",korean:"근면",pos:"noun",example:"Success requires diligence and perseverance.",korExample:"성공은 근면과 인내를 필요로 합니다."},
    {id:8,english:"discernment",korean:"통찰력",pos:"noun",example:"The judge showed great discernment.",korExample:"판사는 뛰어난 통찰력을 보였습니다."},
    {id:9,english:"discreet",korean:"신중한",pos:"adjective",example:"We must be discreet about this matter.",korExample:"우리는 이 문제에 대해 신중해야 합니다."},
    {id:10,english:"disdain",korean:"경멸",pos:"noun",example:"He regarded them with obvious disdain.",korExample:"그는 명백한 경멸로 그들을 대했습니다."},
    {id:11,english:"disparage",korean:"폄하하다",pos:"verb",example:"He constantly disparaged her achievements.",korExample:"그는 끊임없이 그녀의 업적을 폄하했습니다."},
    {id:12,english:"disparity",korean:"불균형",pos:"noun",example:"The wealth disparity continues to grow.",korExample:"부의 불균형이 계속 커지고 있습니다."},
    {id:13,english:"dispassionate",korean:"냉정한",pos:"adjective",example:"The judge maintained a dispassionate demeanor.",korExample:"판사는 냉정한 태도를 유지했습니다."},
    {id:14,english:"dispel",korean:"불식시키다",pos:"verb",example:"The evidence helped dispel doubts.",korExample:"증거는 의혹을 불식시키는 데 도움이 되었습니다."},
    {id:15,english:"disseminate",korean:"보급하다",pos:"verb",example:"We need to disseminate this information widely.",korExample:"우리는 이 정보를 광범위하게 보급해야 합니다."},
    {id:16,english:"dissent",korean:"반대 의견",pos:"noun",example:"The regime suppressed political dissent.",korExample:"그 정권은 정치적 반대 의견을 억압했습니다."},
    {id:17,english:"dissertation",korean:"논문",pos:"noun",example:"She is writing her doctoral dissertation.",korExample:"그녀는 박사 논문을 쓰고 있습니다."},
    {id:18,english:"dissident",korean:"반체제 인사",pos:"noun",example:"The dissident was imprisoned for his views.",korExample:"그 반체제 인사는 자신의 견해 때문에 투옥되었습니다."},
    {id:19,english:"dissipate",korean:"소멸시키다",pos:"verb",example:"The morning fog began to dissipate.",korExample:"아침 안개가 소멸되기 시작했습니다."},
    {id:20,english:"dissolute",korean:"방탕한",pos:"adjective",example:"He led a dissolute lifestyle.",korExample:"그는 방탕한 생활 방식을 이끌었습니다."},
    {id:21,english:"dissuade",korean:"단념시키다",pos:"verb",example:"Nothing could dissuade her from her plan.",korExample:"어떤 것도 그녀를 계획에서 단념시킬 수 없었습니다."},
    {id:22,english:"diverge",korean:"갈라지다",pos:"verb",example:"Their opinions diverged on this issue.",korExample:"이 문제에 대한 그들의 의견은 갈라졌습니다."},
    {id:23,english:"divulge",korean:"누설하다",pos:"verb",example:"He refused to divulge confidential information.",korExample:"그는 기밀 정보를 누설하기를 거부했습니다."},
    {id:24,english:"docile",korean:"순종적인",pos:"adjective",example:"The animal was surprisingly docile.",korExample:"그 동물은 놀랍도록 순종적이었습니다."},
    {id:25,english:"dogmatic",korean:"독단적인",pos:"adjective",example:"His dogmatic approach alienated colleagues.",korExample:"그의 독단적인 접근은 동료들을 소외시켰습니다."},
    {id:26,english:"duplicity",korean:"이중성",pos:"noun",example:"His duplicity was eventually exposed.",korExample:"그의 이중성은 결국 폭로되었습니다."},
    {id:27,english:"duress",korean:"강요",pos:"noun",example:"The confession was made under duress.",korExample:"그 자백은 강요 하에 이루어졌습니다."},
    {id:28,english:"ebullient",korean:"열정적인",pos:"adjective",example:"She was ebullient about the news.",korExample:"그녀는 그 소식에 대해 열정적이었습니다."},
    {id:29,english:"eccentric",korean:"괴짜의",pos:"adjective",example:"The professor had eccentric habits.",korExample:"그 교수는 괴짜의 습관이 있었습니다."},
    {id:30,english:"eclectic",korean:"절충적인",pos:"adjective",example:"His taste in music is quite eclectic.",korExample:"그의 음악 취향은 상당히 절충적입니다."},
    {id:31,english:"edify",korean:"교화하다",pos:"verb",example:"The lecture was meant to edify students.",korExample:"그 강의는 학생들을 교화하기 위한 것이었습니다."},
    {id:32,english:"efficacy",korean:"효능",pos:"noun",example:"The study proved the drug's efficacy.",korExample:"연구는 약물의 효능을 입증했습니다."},
    {id:33,english:"effrontery",korean:"뻔뻔스러움",pos:"noun",example:"He had the effrontery to demand more money.",korExample:"그는 더 많은 돈을 요구할 뻔뻔스러움을 가졌습니다."},
    {id:34,english:"egalitarian",korean:"평등주의적인",pos:"adjective",example:"The society embraced egalitarian principles.",korExample:"그 사회는 평등주의적인 원칙을 받아들였습니다."},
    {id:35,english:"egregious",korean:"심각한",pos:"adjective",example:"The error was egregious and inexcusable.",korExample:"그 오류는 심각하고 용서할 수 없었습니다."}
],

    // ... Level 9-20 계속
};

// 참고: Level 3-20의 전체 데이터는 각각 35-50개씩 작성 필요